---
title: "Story Board Visualization"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
```

Analysis {.storyboard}
=========================================

### Frame 1

```{r}
# Settin up data
cd <- read_csv("C:/Users/demon/Desktop/custodial-deaths.csv")
cd1<-cd[,1:12]
remove(cd)
newnames<-c("Department.Name", "Custody.Type", "Custody.Type.Facility","First.Name","Middle.Name","Last.Name","Ethnicity","Sex","Age","Death.Date","Manner.Death","Charges.Status")
colnames(cd1)<-newnames

# Plotting 
p1<-ggplot(data = cd1, aes(x=Custody.Type, y=Age, colour=Ethnicity))+geom_boxplot()+coord_flip()
p1
```

### Frame 2

```{r}
p2<-ggplot(data=cd1, aes(x=Sex,fill=Charges.Status))+geom_bar(width=1)+coord_polar(theta="y")
p2
```

### Frame 3

```{r}
p3<-ggplot()
```  

### Frame 4

```{r}
```  

### Frame 5

```{r}
```  

### Frame 6

```{r}
```

Details
=========================================

Column
-----------------------------------------
